PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS DRAWINGS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SHAPES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    drawing_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    x1 REAL,
    y1 REAL,
    x2 REAL,
    y2 REAL,
    color TEXT,
    stroke TEXT,
    extra_data TEXT,
    FOREIGN KEY(drawing_id) REFERENCES DRAWINGS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOGS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    action TEXT,
    message TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS NODES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    drawing_id INTEGER NOT NULL,
    label TEXT,
    x REAL,
    y REAL,
    FOREIGN KEY(drawing_id) REFERENCES DRAWINGS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EDGES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    drawing_id INTEGER NOT NULL,
    source_node TEXT,
    target_node TEXT,
    weight REAL,
    FOREIGN KEY(drawing_id) REFERENCES DRAWINGS(id) ON DELETE CASCADE
);
